// <auto-generated />
namespace HamroSite.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_StudentReg_To_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_StudentReg_To_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "202203020728189_Added_StudentReg_To_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
